"""Plain-English notes for flagged values, generated by a small local model.

The template is intentionally strict: the model is told what a test
measures and where the value fell, and asked to explain in plain terms. It
is never asked to diagnose, and a fixed clinician sentence is always
appended so the guidance holds even if the model ignores the instruction.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request

from labexplain.config import Config
from labexplain.models import MatchedRow

CLINICIAN_LINE = "Discuss this result with a doctor or other clinician who has your full history."

SYSTEM_PROMPT = (
    "You are a lab report explainer for a general reader with no medical training. "
    "You explain what ONE blood test value means in plain, calm English. "
    "Rules you must always follow: "
    "1) Never name or suggest a specific disease, condition, or diagnosis. "
    "2) Never recommend a medication, supplement, dosage, or treatment. "
    "3) Never tell the reader what to do next beyond seeing a clinician. "
    "4) Keep it factual and under 4 short sentences. "
    "5) If you are unsure what the test measures, say so plainly instead of guessing. "
    "6) Always end with a sentence telling the reader to discuss the result with a clinician."
)


class ExplainError(RuntimeError):
    pass


def _status_label(status: str) -> str:
    return {
        "low": "below the reference range",
        "high": "above the reference range",
        "critical_low": "well below the reference range",
        "critical_high": "well above the reference range",
    }.get(status, status)


def build_prompt(row: MatchedRow) -> str:
    range_text = "not established" if row.low is None and row.high is None else f"{row.low}-{row.high}"
    return (
        f"Test: {row.display_name}\n"
        f"Result: {row.value} {row.unit or ''}\n"
        f"Reference range: {range_text} {row.unit or ''}\n"
        f"This result is {_status_label(row.status)}.\n\n"
        "In 2 to 4 sentences, explain in plain English what this test generally measures "
        "and what it can mean, in general terms, for a result to fall outside the reference "
        "range like this one. Do not diagnose. Do not recommend treatment."
    )


def _ensure_clinician_line(text: str) -> str:
    text = text.strip()
    if CLINICIAN_LINE.lower()[:30] in text.lower():
        return text
    if not text.endswith((".", "!", "?")):
        text += "."
    return f"{text} {CLINICIAN_LINE}"


def explain_row(row: MatchedRow, cfg: Config) -> str:
    payload = {
        "model": cfg.ollama_explain_model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_prompt(row)},
        ],
        "stream": False,
        "think": False,
        "options": {"temperature": 0.2, "num_predict": cfg.max_explain_tokens},
    }
    req = urllib.request.Request(
        cfg.ollama_url.rstrip("/") + "/api/chat",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        raise ExplainError(f"Ollama returned HTTP {exc.code}") from exc
    except (urllib.error.URLError, OSError) as exc:
        raise ExplainError(f"Ollama is not reachable at {cfg.ollama_url}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ExplainError(f"Ollama sent a malformed response: {exc}") from exc
    if "error" in data:
        raise ExplainError(f"Ollama error: {data['error']}")
    text = data.get("message", {}).get("content", "").strip()
    if not text:
        raise ExplainError("Ollama returned an empty explanation")
    return _ensure_clinician_line(text)
